### ISSUE TITLE
"Location Name" moved to before "Street Address"

### ISSUE THREAD

**Issue by catheraaine** [sparkbox/local-events-project#115]
Currently Rails Admin is in this order:

Name:
Image:
When:
Description:
Recurring:
Street Address: 
City:
State:
Zip: 
Location Name: 

Natural flow, should be in this order: 

Name:
Description:
When:
Recurring:
Location Name: 
Street Address: 
City:
State:
Zip: 
Image:

**Comment by catheraaine** [comment]
Requires a scrub of the database.

**Comment by drewclemens** [comment]
not doing this
