### ISSUE TITLE
IE9 Issues

### ISSUE THREAD

**Issue by BC3209** [sparkbox/local-events-project#168]
additional scroll bars
<img width="1440" alt="additional scroll bars" src="https://cloud.githubusercontent.com/assets/8916304/15831238/a23ad52c-2bea-11e6-802c-c73bd5d77ea9.png">

No text-wrap on individual cards only happening on a few 9/10
<img width="1440" alt="no text-wrap on individual cards only happening on a few 9 10" src="https://cloud.githubusercontent.com/assets/8916304/15831243/a24fac72-2bea-11e6-850b-4eff366a9bae.png">

Overlapping
<img width="1440" alt="overlapping" src="https://cloud.githubusercontent.com/assets/8916304/15831240/a24dcc86-2bea-11e6-9088-11f81aa0106a.png">

More overlapping
<img width="1440" alt="screen shot 2016-06-06 at 11 04 18 am" src="https://cloud.githubusercontent.com/assets/8916304/15831241/a24eeb20-2bea-11e6-9c2a-321992fb851e.png">

Text being cut off
<img width="1440" alt="screen shot 2016-06-06 at 11 10 39 am" src="https://cloud.githubusercontent.com/assets/8916304/15831239/a24b09e2-2bea-11e6-9036-c182b730c748.png">

Weird things happening with the side nav...Goes back to normal after a few seconds
<img width="1440" alt="screen shot 2016-06-06 at 11 13 05 am" src="https://cloud.githubusercontent.com/assets/8916304/15831244/a259ad3a-2bea-11e6-839a-02b1166727fb.png">

Some images not loading
<img width="1440" alt="some images are not loading" src="https://cloud.githubusercontent.com/assets/8916304/15831245/a26898a4-2bea-11e6-8944-7c12be77ff9e.png">

**Comment by drewclemens** [comment]
moved to other cards
