### ISSUE TITLE
Very Basic Comprehensive Styles

### ISSUE THREAD

**Issue by catheraaine** [sparkbox/local-events-project#195]
- [ ] basic link styles
- [ ] blockquotes
- [ ] unordered lists
- [ ] ordered lists
- [ ] all 6 header tags
- [ ] inline images (left, right, center, etc in CMS content)
- [ ] print stylesheet

**Comment by drewclemens** [comment]
I'm going to create a new one for print style sheet. The rest aren't necessary for this project at this time.
