### ISSUE TITLE
Accessibility - a11y / aXe fixes are necessary

### ISSUE THREAD

**Issue by catheraaine** [sparkbox/local-events-project#196]
Run the aXe extensions and fix

**Comment by iAmNathanJ** [comment]
@boomingbrake @catheraaine @BC3209 

Whoever does this, make sure you run aXe as you make changes. Tags that are semantically correct shouldn't need aria roles, and may actually give errors if they are added, but unnecessary.

**Comment by catheraaine** [comment]
It's pretty good. It is yelling about contrast on the address and sharable link, but nothing else really.
