### ISSUE TITLE
List of Events on a page (will be homepage)

### ISSUE THREAD

**Issue by drewclemens** [sparkbox/local-events-project#8]
* [ ] empty state
* [x] multiple event titles in a list coming from Ruby app
* [x] passing relevant tests in Circle CI
* [x] reasonably passing Code Climate
* [x] accessible
* [x] documentation

This is the first pass on this page. No styles or full experience required. Only the list of events in good markup is required.

**Comment by boomingbrake** [comment]
Created Events Controller and events/index.html.erb.
